---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

ENABLE:
  - TERRAFORM
  - POWERSHELL
  - YAML

PRINT_ALL_FILES: true
SHOW_ELAPSED_TIME: true
TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES: [GITHUB_TOKEN]
TERRAFORM_TERRASCAN_ARGUMENTS: -d ./terraform
